# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lCNCzNFJIVYfhQbq7qLvBKm85pd_oUuC
"""

# ==============================
# DSA Question Recommendation System
# TF-IDF + KNN (Machine Learning)
# ==============================

# Upload Dataset
from google.colab import files
uploaded = files.upload()

# Import Libraries
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.neighbors import NearestNeighbors

# Load Dataset
filename = list(uploaded.keys())[0]
df = pd.read_csv(filename)

print("Dataset Loaded Successfully")
print("Shape:", df.shape)

# Display Columns
print("\nAvailable Columns:")
print(df.columns.tolist())

# --------------------------------
# CHANGE THESE IF YOUR DATASET
# HAS DIFFERENT COLUMN NAMES
# --------------------------------
TITLE_COL = 'title'
TOPIC_COL = 'related_topics'
DIFFICULTY_COL = 'difficulty'

# Keep Required Columns
df = df[[TITLE_COL, TOPIC_COL, DIFFICULTY_COL]]

# Handle Missing Values
df[TOPIC_COL] = df[TOPIC_COL].fillna('')
df[DIFFICULTY_COL] = df[DIFFICULTY_COL].fillna('')

# Combine Features
df['features'] = (
    df[TOPIC_COL].astype(str) +
    ' ' +
    df[DIFFICULTY_COL].astype(str)
)

# TF-IDF Vectorization
vectorizer = TfidfVectorizer(stop_words='english')

X = vectorizer.fit_transform(df['features'])

print("\nTF-IDF Shape:", X.shape)

# Train KNN Model
model = NearestNeighbors(
    n_neighbors=6,
    metric='cosine'
)

model.fit(X)

print("KNN Model Trained Successfully!")

# Recommendation Function
def recommend(question_name, top_n=5):

    matches = df[
        df[TITLE_COL].str.lower() ==
        question_name.lower()
    ]

    if len(matches) == 0:
        print("Question not found!")
        return

    idx = matches.index[0]

    distances, indices = model.kneighbors(
        X[idx],
        n_neighbors=top_n + 1
    )

    print("\nRecommended Questions:")
    print("-" * 50)

    for i in range(1, len(indices[0])):

        rec_idx = indices[0][i]

        print(
            f"{i}. {df.iloc[rec_idx][TITLE_COL]}"
        )

        print(
            f"   Difficulty: {df.iloc[rec_idx][DIFFICULTY_COL]}"
        )

        print(
            f"   Similarity: {(1 - distances[0][i])*100:.2f}%"
        )

        print()

# Interactive Loop
while True:

    q = input(
        "\nEnter Question Name (or 'exit'): "
    )

    if q.lower() == 'exit':
        print("Goodbye!")
        break

    recommend(q)